### ISSUE TITLE
Encountering "current database router prevents this relation" with single database

### ISSUE THREAD

**Issue by GregoryAveryWeir** [dcramer/mock-django#30]
Given that I'm not seeing others encountering this issue, it may be something wrong with my code, but I'm seeing "ValueError: Cannot assign "<_ModelMock spec='Account' id='180462412'>": the current database router prevents this relation." when trying to instantiate a model using mocked attributes.

Google indicates that this error occurs when trying to make a relation that spans DBs, but I have a single sqlite DB. I assume the issue is that the mocked ID doesn't exist in the test DB.

Is there something wrong with the way I'm using mock_django? 

Example code:
```python
from django.utils import unittest
from django.contrib.auth.models import User

from mock_django import ModelMock

from accounts.models import Account
from badges.models import Badge

class EarnedUnitTestCase(unittest.TestCase):
    def test_earned_unicode(self):
        account = ModelMock(Account)
        badge = ModelMock(Badge)

        earned = Earned(account=account, badge=badge)
        self.assertEqual(unicode(earned), "Account's Badge")
```

**Comment by mariocesar** [comment]
Adding this properties will make it work:

```
account._state = Mock()
account._state.db = None
badge._state = Mock()
badge._state.db = None
```

**Comment by pilamb** [comment]
Hi

I have found these instructions  because I was having the: 
_(raise ValueError('Cannot assign "%r": the current database router prevents this relation.' % value)
ValueError: Cannot assign "<Mock spec='Token' id='4592472472'>": the current database router prevents this relation)_
error and now doing what @mariocesar suggested got the following error:

```
Traceback (most recent call last):
  File "/Users/r/Developing/w/w/wallets/tests.py", line 32, in setUp
    self.wallet = Wallet.objects.create(owner=owner, token=token)
  File "/Users/r/.virtualenvs/w/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/r/.virtualenvs/w/lib/python3.7/site-packages/django/db/models/query.py", line 411, in create
    obj = self.model(**kwargs)
  File "/Users/r/.virtualenvs/w/lib/python3.7/site-packages/django/db/models/base.py", line 467, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/r/.virtualenvs/w/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 300, in __set__
    super().__set__(instance, value)
  File "/Users/r/.virtualenvs/w/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 257, in __set__
    remote_field.set_cached_value(value, instance)
  File "/Users/r/.virtualenvs/w/lib/python3.7/site-packages/django/db/models/fields/mixins.py", line 23, in set_cached_value
    instance._state.fields_cache[self.get_cache_name()] = value
TypeError: 'Mock' object does not support item assignment
```

This is the piece of code which is raising the traceback above:

```
from mock_django import ModelMock
from mock import Mock
***
  def setUp(self):
        owner = ModelMock(Client)
        owner._state = Mock()
        owner._state.db = None
        token = ModelMock(Token)
        token._state = Mock()
        token._state.db = None
        self.wallet = Wallet.objects.create(owner=owner, token=token)
```

Owner and Token are OneToOne and ForeignKey to other models. 

Is there a way to be able to save related ModelMocked objects?

Its been run locally: Python3.7 on djangorestframework==3.9.2.

Thanks in advance

**Comment by zohrehhanza** [comment]
@pilamb I have the same problem, did you find the solution?
